import type { JobDto, DashboardStatsDto } from '@/domain';

export const MOCK_STATS: DashboardStatsDto = {
  total: 450,
  pending: 320,
  applied: 85,
  interview: 30,
  accepted: 15,
};

export const MOCK_JOBS: JobDto[] = [
  {
    id: '1',
    companyName: 'Google',
    industry: '科技業',
    jobTitle: 'Senior Frontend Engineer',
    level: 'senior',
    status: 'interview',
    salary: 'NT$ 120,000 - 180,000',
    skills: ['React', 'TypeScript', 'GraphQL'],
    source: 'linkedin',
    postedDate: '2024-01-15',
    url: 'https://example.com/job/1',
  },
  {
    id: '2',
    companyName: 'TSMC',
    industry: '半導體',
    jobTitle: 'Full Stack Developer',
    level: 'mid',
    status: 'applied',
    salary: 'NT$ 80,000 - 120,000',
    skills: ['Vue', 'Node.js', 'PostgreSQL'],
    source: '104',
    postedDate: '2024-01-14',
    url: 'https://example.com/job/2',
  },
  {
    id: '3',
    companyName: 'Shopee',
    industry: '電商',
    jobTitle: 'Backend Engineer',
    level: 'junior',
    status: 'pending',
    salary: 'NT$ 60,000 - 90,000',
    skills: ['Go', 'Kubernetes', 'Redis'],
    source: 'yourator',
    postedDate: '2024-01-13',
    url: 'https://example.com/job/3',
  },
  {
    id: '4',
    companyName: 'LINE',
    industry: '科技業',
    jobTitle: 'Tech Lead',
    level: 'lead',
    status: 'accepted',
    salary: 'NT$ 150,000 - 220,000',
    skills: ['Java', 'Spring Boot', 'AWS'],
    source: 'cakeresume',
    postedDate: '2024-01-12',
    url: 'https://example.com/job/4',
  },
  {
    id: '5',
    companyName: 'Appier',
    industry: 'AI',
    jobTitle: 'ML Engineer',
    level: 'senior',
    status: 'rejected',
    salary: 'NT$ 100,000 - 160,000',
    skills: ['Python', 'TensorFlow', 'Docker'],
    source: 'linkedin',
    postedDate: '2024-01-11',
    url: 'https://example.com/job/5',
  },
];
